name: Build NAVARA Mobile APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Extract project
        run: |
          unzip -q SAMP-Mobile-GTA-2.11.zip -d project
          mkdir -p project/SAMP-Mobile-GTA-2.11/app/src/main/cpp/samp/gui/samp_widgets
          cp playerTabList.h project/SAMP-Mobile-GTA-2.11/app/src/main/cpp/samp/gui/samp_widgets/playerTabList.h

      - name: Build APK
        working-directory: project/SAMP-Mobile-GTA-2.11
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NAVARA-Mobile-APK
          path: project/SAMP-Mobile-GTA-2.11/app/build/outputs/apk/**/*.apk
